### ISSUE TITLE
Use `getopts` to handle CLI arguments in lower-level scripts

### ISSUE THREAD

**Issue by atreyasha** [archlinux-downgrade/downgrade#182]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background

Currently, we handle CLI argument parsing on our own (i.e. without external tools).

### Proposed feature

Our workflow would benefit from using `getopt` to aid CLI argument parsing.

**Comment by atreyasha** [comment]
We should use POSIX's `getopts` instead of Bash's `getopt` for reasons mentioned here:

https://github.com/archlinux-downgrade/downgrade/pull/196#discussion_r854453235

**Comment by pbrisbin** [comment]
I'm OK not doing this. If it happens great, if not no worries.
