### ISSUE TITLE
`downgrade-11.2.0-1` does not appear to build with `paru

### ISSUE THREAD

**Issue by a2n-s** [archlinux-downgrade/downgrade#205]
### Checklist

- [x] No duplicate issues/PRs
- [ ] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Environment

* System information:

`Linux archasus 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux`

* Downgrade version:

`11.1.0`

### Description

When running `paru` to update my whole system, the update of `downgrade` does not succeed.

The full error is the following:
```bash
install: cannot stat 'bin//usr/local/bin': No such file or directory
install: cannot stat 'completion//usr/local/bin/bash': No such file or directory
install: cannot stat 'completion//usr/local/bin/zsh': No such file or directory
install: cannot stat 'completion//usr/local/bin/fish': No such file or directory
make: *** [Makefile:41: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'downgrade-11.2.0-1':
error: packages failed to build: downgrade-11.2.0-1
```

**Comment by atreyasha** [comment]
Thanks @a2n-s for reporting this issue.

## Cause

Just by looking at the log you posted and comparing it with our `Makefile`, I can tell that the issue arises from the variable `$script` being incorrectly resolved as `/usr/local/bin`:

https://github.com/archlinux-downgrade/downgrade/blob/30efdf7871b19c3385d1850e824b0d34acbd5a34/Makefile#L41-L45

## Reproduction

I don't experience this issue when installing or upgrading via `makepkg` or with the `yay` helper.

As I don't use `paru`, I tried a dockerized workflow to reproduce this issue with the following `Dockerfile`:

```Dockerfile
# get base docker image
FROM greyltc/archlinux-aur:paru-20220605.0.219

# verify paru version
RUN paru --version

# enable wheel group to access sudo without password
RUN sed -i '/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^# *//g' /etc/sudoers

# add a test user to the wheel group
RUN useradd -G wheel -m test

# switch to the test user
USER test
WORKDIR /home/test

# clone downgrade from AUR
RUN git clone https://aur.archlinux.org/downgrade.git
WORKDIR /home/test/downgrade

# checkout and install downgrade v11.1.0
RUN git reset --hard c4ab93918ecb7e350986a4c2b54702cedd1667ec
RUN makepkg --noconfirm -si

# verify that downgrade version is v11.1.0
RUN which downgrade
RUN downgrade --version

# start system upgrade including donwgrade
RUN paru -Syu --noconfirm

# verify that downgrade version is v11.2.0
RUN which downgrade
RUN downgrade --version
```

I ran this with the following command (assuming this `Dockerfile` exists in the same directory):

```
$ docker build . -t test_downgrade_issue_205:latest
```

No similar error was encountered during the system upgrade and `downgrade` was successfully upgraded.

## Debugging

I am not sure if this error arose from `paru` or something more local. Do you encounter a similar error when you install the latest `downgrade` via `makepkg` (see helper commands below)?

```
$ git clone https://aur.archlinux.org/downgrade.git
$ cd downgrade
$ makepkg -si
```

**Comment by a2n-s** [comment]
**yay**:
```bash
yay -S downgrade
``` 
gives me a similar issue
```bash
install: cannot stat 'bin//usr/local/bin': No such file or directory
install: cannot stat 'completion//usr/local/bin/bash': No such file or directory
install: cannot stat 'completion//usr/local/bin/zsh': No such file or directory
install: cannot stat 'completion//usr/local/bin/fish': No such file or directory
make: *** [Makefile:41: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: downgrade
```

**manual install via `makepkg`**:
and I get the exact same errors. i.e.
```bash
install: cannot stat 'bin//usr/local/bin': No such file or directory
install: cannot stat 'completion//usr/local/bin/bash': No such file or directory
install: cannot stat 'completion//usr/local/bin/zsh': No such file or directory
install: cannot stat 'completion//usr/local/bin/fish': No such file or directory
make: *** [Makefile:41: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```
with either `makepkg -si` or `makepkg -cf`

**docker**:
the image and the `build` command you give work...

**that looks like something local** :sob:

**Comment by atreyasha** [comment]
Ah I see. Yes that seems like something local. My guess would be there is some (probably environmental) variable called `script` that gets defined as `/usr/local/bin`. Maybe your shell and pacman configs could be places to look.

AFAICT, this does not seem like a `downgrade` specific problem and I would be inclined to close this issue. But then again if this `script` variable is causing conflicts then we could rename it to something less generic like `downgrade_script`.

@pbrisbin WDYT?

**Comment by pbrisbin** [comment]
Since we can't seem to reproduce this, and the user can't reproduce in a clean environment (docker) either, I'd say it's not a bug on our end.

Since we're using a lower-case variable `$script`, I don't think we're in the wrong to expect that we own it and it's not coming in from the environment. If something is utilizing some kind of environment variable, it should be capitalized (IMO), exactly to prevent collisions such as this. That said, we could certainly choose some other variable name; there's little downside. Setting up some convention like `$_script` or `$script_` for all our internal variables could be a good better-safe-than-sorry.

Personally, I suspect this is a zsh issue. It loves to use lower-case variables for things. If you redefine `path` it can cause all sorts of problems, for example. And "script" seems like a thing zsh may care about and set up its own variable for (e.g. "the currently executing file" or something).

**Comment by a2n-s** [comment]
Really great job guys :ok_hand:

It was a purely local issue of mine indeed and I feel quite confused about that :eyes:

I immediattely understood that it was the `$script` variable the trouble maker :thinking: 
In fact, to launch my `bspwm` config, I `export` some environment variables, e.g. to control some bindings through `sxhkd`.
I tried to make sure I `export` all of them with the `WM_` prefix, precisely to avoid that kind of strange error! But `$SCRIPT` was not part of the `WM_` familly :laughing: 

It works just fine now, as all my `bspwm`, and WM in general, variables are `export`ed with the `WM_` prefix! :tada: 

Thanks again @atreyasha and @pbrisbin for your fast and really good comments :wink: :star_struck:
