### ISSUE TITLE
Downgrade system upgrade from pacman log

### ISSUE THREAD

**Issue by UltraBlackLinux** [archlinux-downgrade/downgrade#209]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background
Sometimes you don't have something like btrfs available to easily restore a previous snapshot if an update badly breaks some programs

### Proposed feature
I think it would be really useful if you could rollback a whole update via `downgrade`. This could be parsed out of the pacman.log together with a given timeframe in minutes

**Comment by atreyasha** [comment]
Thanks for the feature request.

I like the idea and it could integrate well with the version filtering operators that `downgrade` already supports:

```console
$ print_packages_before_upgrade -t 10  # within the last 10 minutes
foo=1.0.0
bar=2.0.0

$ print_packages_before_upgrade | downgrade -
```

The `print_package_before_upgrade` utility would parse `pacman.log` looking at both the timestamps and keywords such as `upgraded` to get the versions of packages before the upgrade (using regular expressions for example). This utility would have to be created and packaged as part of `downgrade`, either as a separate script or within the `bin/downgrade` script.

## Caveats

1. A full rollback would imply that we uninstall or install packages that were installed or uninstalled previously during the upgrade. This is something difficult to do via `downgrade` alone and I'm not sure if or how we could support this part.
2. Features like this and #208 push the limits of what we'd want to write in bash. There was some concensus in #208 to use Python, so perhaps this feature could be written in Python too.

@pbrisbin WDYT?

**Comment by atreyasha** [comment]
A simpler alternative could be to rollback to a daily snapshot of the A.L.A. as described below:

https://wiki.archlinux.org/title/Arch_Linux_Archive#How_to_restore_all_packages_to_a_specific_date

This could be more easily done in bash as it only involves an update of `pacman.conf` followed by a system update. But this alternative would not address the original issue directly.

**Comment by pbrisbin** [comment]
Closing this as not planned (by us), but patches welcome!
