### ISSUE TITLE
Option to not ask to add IgnorePkg

### ISSUE THREAD

**Issue by lilydjwg** [archlinux-downgrade/downgrade#210]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background

I have several `IgnorePkg` lines, some with comments explaining why they are ignored. But downgrade will rewrite it to put all ignored packages on one line.

### Proposed feature

Add an option to not ask to add `IgnorePkg` so the user won't forget the behavior and accidentally rewrite them again and again.

**Comment by pbrisbin** [comment]
Sounds reasonable to me!
