### ISSUE TITLE
Remove switches from configuration comment

### ISSUE THREAD

**Issue by krumelmonster** [archlinux-downgrade/downgrade#218]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

The default downgrade.conf says

```
# Defaults are shown, uncomment and define values as desired
```

But both `--ala-only` and `--cached-only` are shown which would behave as if only `--cached-only` was given (this could be considered as another bug). If command line arguments should be "overwrites" to the config file, maybe all options should have an opposite counterpart e.g. `--ala-only no` or completely diffferent like `--ala|--no-ala` or `--source <cache|ala|any>`.

I chose to not add the command line switch in my pr https://github.com/archlinux-downgrade/downgrade/pull/217 to `conf/downgrade.conf` because it is not (supposed to be) default.

**Comment by pbrisbin** [comment]
Good catch, I can see how that'd be confusing. I think if we want to keep the "Defaults are shown" note, we need to simply remove both of the commented `-only` options, as not passing them represents the "defaults". The comment already directs the user to the real man-page, so I don't think omitting them is any kind of problem.
