### ISSUE TITLE
Fzf menu keymaps

### ISSUE THREAD

**Issue by niksingh710** [archlinux-downgrade/downgrade#222]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Environment

* System information: 
```bash
Linux mach 6.6.10-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:18 +0000 x86_64 GNU/Linux
```

* Downgrade version:
```bash
11.3.0
```

### Questions/Help
The Fzf menu that pops up, is there any way to change the key mapping to scroll in that menu?

**Comment by pbrisbin** [comment]
> is there any way to change the key mapping to scroll in that menu?

There is no way directly supported by Downgrade. We would have to add that feature.

I don't know if Fzf itself respects any environment variables you could use to adjust its behavior when used from within downgrade. I'm relatively confident it supports a configuration file, but that would affect all uses and not just downgrade, which may or may not be good with you.

**Comment by niksingh710** [comment]
@pbrisbin Fzf supports environment variables but not sure if that will work inside downgrade as it supports for it's own specific command like `c-t`.
if downgrade can accept an arg like `--fzf-flags="--bind=\"ctrl-n:...\""` so that the user can pass flags to fzf by himself.

**Comment by pbrisbin** [comment]
> Fzf supports environment variables but not sure if that will work inside downgrade

Maybe I'm misunderstanding, but `downgrade` wouldn't do anything to _prevent_ whatever Fzf is supporting from working. So if `FZF_OPTIONS=x fzf ...` does something, then `FZF_OPTIONS=x downgrade ...` should do the same thing.
