### ISSUE TITLE
Add documentation for AUR package downgrading

### ISSUE THREAD

**Issue by KAGEYAM4** [archlinux-downgrade/downgrade#223]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background

I tried downgrading packages which i got from AUR using yay which are caches in `~/.cace/yay` but downgrading failed - `No results found`

### Proposed feature

Add support for downgrading AUR packages by using yay/paru cached packages.

**Comment by atreyasha** [comment]
Does it work with this?

```
# downgrade --pacman-cache ~/.cache/yay --maxdepth 2 <aur_pkg>
```

You can set these options persistently in `/etc/xdg/downgrade/downgrade.conf` and specify the `--pacman-cache` option multiple times to cover both standard and AUR cache locations, eg. `--pacman-cache /var/cache/pacman/pkg --pacman-cache ~/.cache/yay`.

**Comment by KAGEYAM4** [comment]
> Does it work with this?
> 
> ```
> # downgrade --pacman-cache ~/.cache/yay --maxdepth 2 <aur_pkg>
> ```
> 
> You can set these options persistently in `/etc/xdg/downgrade/downgrade.conf` and specify the `--pacman-cache` option multiple times to cover both standard and AUR cache locations, eg. `--pacman-cache /var/cache/pacman/pkg --pacman-cache ~/.cache/yay`.

Yuup this works, thank you.

Maybe add this to readme.

**Comment by KAGEYAM4** [comment]
i will keep it open, so that you can track it for the documentation PR.


Also, can we use shell variable in the .conf file like - `--pacman-cache /home/${USER}/.cache/yay` ?

**Comment by atreyasha** [comment]
> i will keep it open, so that you can track it for the documentation PR.

Thanks!

> Also, can we use shell variable in the .conf file like - --pacman-cache /home/${USER}/.cache/yay ?

Unfortunately that does not work in the configuration file, as `downgrade` is run as root and does not have knowledge of the non-root user during execution. So it would have to be the full (expanded) path.
