### ISSUE TITLE
downgrade not work on specific package

### ISSUE THREAD

**Issue by shilkazx** [archlinux-downgrade/downgrade#227]
I wanna downgrade tzdata package, but when I run downgrade, it not show the historical version list but just behave like normal installation process:
```
sudo downgrade tzdata                                                                                                                                                  1 
loading packages...
warning: tzdata-2024b-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) tzdata-2024b-1

Total Installed Size:  1.93 MiB
Net Upgrade Size:      0.00 MiB
```
I've tried some other package: vim/gvim behave normal but firefox behave just like tzdata.

**Comment by pbrisbin** [comment]
Hmm, I can't seem to reproduce this. When I run `sudo downgrade tzdata` I get a big list. Can you please fill out the rest of the ISSUE_TEMPLATE? Particularly, system information and a "trace" (`sudo bash -x downgrade tzdata`).

**Comment by shilkazx** [comment]
It's drive me nuts. I can't reproduce this on my office today. The only thing changed is time and network. But I suspect the problem is not related to network(I've checked the network connection before I report the bug), Maybe it's caused by temporary failure/bug of archive website?  
p.s. I use Archlinux x64 and update the packages day by day.

**Comment by xlucn** [comment]
I am having this as well. It seems that https://archive.archlinux.org/ is giving me 403. But I can access the site through a VPN. So probably we are blocked by the website, reasons unknown.
