### ISSUE TITLE
downgrade not working

### ISSUE THREAD

**Issue by OTAKUWeBer** [archlinux-downgrade/downgrade#228]
/usr/local/bin/downgrade: line 213: pacsort: command not found
No results found
Unable to downgrade pacman

**Comment by OTAKUWeBer** [comment]
firstly downloaded 

> `pacsort` is provided by `pacman-contrib`:
> 
> ```
> % pacman -Ql pacman-contrib | grep pacsort
> pacman-contrib /usr/bin/pacsort
> pacman-contrib /usr/share/man/man8/pacsort.8.gz
> pacman-contrib /usr/share/zsh/site-functions/_pacsort
> ```
> 
> Which is listed as a dependency: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=downgrade#n13
> 
> ```shell
> depends=('pacman-contrib' 'fzf') # pacsort
> ```
> 
> So I believe `downgrade` is configured correctly. How did you install `downgrade`?

worked after downloading using paru ... at first I downloaded using yay. IDK what was the problem

**Comment by pbrisbin** [comment]
> worked after downloading using paru ... at first I downloaded using yay

Sounds me like `yay` just didn't install dependencies. Either because that requires some extra flag you didn't pass, or it has a bug. Glad it's working now!
