### ISSUE TITLE
Check the scenario on armv7h CPU and different archive URL and sudo

### ISSUE THREAD

**Issue by vinibali** [archlinux-downgrade/downgrade#229]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest downgrade release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Proposed feature

Could we add set default DOWNGRADE_ALA_URL for armv7h and aarch64 architectures to

```
https://alaa.ad24.cz
```

Of course, I can set the env_keep in the sudoers, but it would be great to take this URL for not x86_64 architectures.

**Comment by pbrisbin** [comment]
FYI: I re-write the Issue as a feature request.

>  I can set the env_keep in the sudoers

I'm not sure what sudoers has to do with this. Why not configure it via our configuration file?

```sh
# /etc/xdg/downgrade/downgrade.conf.
--ala-url https://alaa.ad24.cz
```

**Comment by vinibali** [comment]
Thanks for the hint, I didn't know that.
The env_keep variable I've mentioned is that if I set the env variable
```
DOWNGRADE_ALA_URL="https://alaa.ad24.cz"
```
this is not getting picked up as I need to run downgrade as sudo.

**Comment by pbrisbin** [comment]
I'm going to close as it looks like using `/etc/xdg/downgrade/downgrade.conf` should work. I realized we don't really have docs on this configuration file anywhere prominent so I will open a new Issue to address that.

**Comment by vinibali** [comment]
thanks
